# Python W4 - Assignment 01

## Q1:  Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [5]:
# Ans:
import numpy as np
x = np.ones((3,3))
print("checkboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

checkboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q2: Create a 2d array with 1 on the border and 0 inside

In [7]:
# Ans:
import numpy as np
x = np.ones((5,5))
print("original array:")
print(x)
print("1 on the boarder and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the boarder and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Q3: Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
# Ans
import numpy as np
x =  np.arange(0,9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


0 to 8 (3x3) not taken so we taken 0-9

## Q4: Create a vector with values ranging from 10 to 49 and then reverse the vector.

In [17]:
# Ans
v= np.arange(10,50)
print (v)
v= v[::-1]
print (v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Q5: Find indices of non-zero elements from the numpy array - [1,2,0,0,4,0]

In [22]:
# Ans 
import numpy as np
nums = np.array([1,2,0,0,4,0])
print("original array:")
print(nums)
print("indices of elements non zero of the said array")
result = np. where(nums !=0)
print(result)

original array:
[1 2 0 0 4 0]
indices of elements non zero of the said array
(array([0, 1, 4]),)


## Q6: Import the pandas library, import the absenteeism dataset(provided) and assign it to “df”, and find out the “type” of the dataset.

In [1]:
#Ans
#import pandas library
import pandas as pd
import numpy as np
# importinf file from a local folder
from google.colab import files
uploaded = files.upload()

Saving Absenteeism_data (7).csv to Absenteeism_data (7) (1).csv


In [39]:
df = pd.DataFrame(dataset)
dataset = pd.read_csv("Absenteeism_data (7).csv")
type(dataset)


pandas.core.frame.DataFrame

## Q7: Find the info of the data set.

In [19]:
#Ans
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   ID                         700 non-null    int64  
 1   Reason for Absence         700 non-null    int64  
 2   Date                       700 non-null    object 
 3   Transportation Expense     700 non-null    int64  
 4   Distance to Work           700 non-null    int64  
 5   Age                        700 non-null    int64  
 6   Daily Work Load Average    700 non-null    float64
 7   Body Mass Index            700 non-null    int64  
 8   Education                  700 non-null    int64  
 9   Children                   700 non-null    int64  
 10  Pets                       700 non-null    int64  
 11  Absenteeism Time in Hours  700 non-null    int64  
dtypes: float64(1), int64(10), object(1)
memory usage: 65.8+ KB


## Q8: Drop the first column “ID”, and save it back to “df”.

In [30]:
#Ans
dataset_drop = dataset.drop(columns=['ID'])
dataset_drop.head()

 

Reason for Absence        Date  Transportation Expense  Distance to Work  \
0                  26  07/07/2015                     289                36   
1                   0  14/07/2015                     118                13   
2                  23  15/07/2015                     179                51   
3                   7  16/07/2015                     279                 5   
4                  23  23/07/2015                     289                36   

   Age  Daily Work Load Average  Body Mass Index  Education  Children  Pets  \
0   33                  239.554               30          1         2     1   
1   50                  239.554               31          1         1     0   
2   38                  239.554               31          1         0     0   
3   39                  239.554               24          1         2     0   
4   33                  239.554               30          1         2     1   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

## Q9: Drop the age column. And save it back to “df”

In [33]:
# Ans
dataset_drop = dataset.drop(columns=["Age"])
dataset_drop.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  11                  26  07/07/2015                     289   
1  36                   0  14/07/2015                     118   
2   3                  23  15/07/2015                     179   
3   7                   7  16/07/2015                     279   
4  11                  23  23/07/2015                     289   

   Distance to Work  Daily Work Load Average  Body Mass Index  Education  \
0                36                  239.554               30          1   
1                13                  239.554               31          1   
2                51                  239.554               31          1   
3                 5                  239.554               24          1   
4                36                  239.554               30          1   

   Children  Pets  Absenteeism Time in Hours  
0         2     1                          4  
1         1     0                          0  
2         0     0                          2  
3         2     0                          4  
4         2     1                          2

## Q10 What are the smallest and largest values of the column “reason for absence”.

In [54]:
import pandas as pd
df =


SyntaxError: ignored